apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mariadb-phpmyadmin-nfs-storage-class
  namespace: mariadb-phpmyadmin
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
